package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/arash16/dualnet/internal/netschema"
	"github.com/arash16/dualnet/internal/release"
	"gopkg.in/yaml.v3"
)

// runCompile expands a root network schema into one <node>.yaml per node.
func runCompile(args []string) error {
	fs := flag.NewFlagSet("compile", flag.ExitOnError)
	netFlag := fs.String("network", "", "network schema path (required)")
	outFlag := fs.String("out", ".", "output directory for per-node configs")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *netFlag == "" {
		return fmt.Errorf("compile: -network is required")
	}
	net, err := netschema.Load(*netFlag)
	if err != nil {
		return err
	}
	// No PSK is taken here on purpose: the global PSK is never baked into a generated config
	// (config.Node.ForArtifact strips it). It is provided out-of-band via DUALNET_PSK at deploy/
	// run time, which overrides the file — so the shipped configs and k8s ConfigMaps carry no
	// shared secret. See internal/release and the deploy.sh/manifest headers.
	nodes, err := net.Compile()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(*outFlag, 0o755); err != nil {
		return err
	}

	names := make([]string, 0, len(nodes))
	for name := range nodes {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		var buf []byte
		// Strip the PSK from the written config: it is delivered out-of-band via DUALNET_PSK
		// (systemd env drop-in / k8s Secret) at deploy time and overrides the file, so the
		// shipped node.yaml never carries the real shared secret.
		out, err := yaml.Marshal(nodes[name].ForArtifact())
		if err != nil {
			return fmt.Errorf("compile: marshal %q: %w", name, err)
		}
		buf = append([]byte(fmt.Sprintf("# Generated by `dualnet compile` from %s — do not edit by hand.\n", filepath.Base(*netFlag))), out...)
		dst := filepath.Join(*outFlag, name+".yaml")
		if err := os.WriteFile(dst, buf, 0o600); err != nil {
			return err
		}
		fmt.Printf("wrote %s\n", dst)
	}

	// When any node declares a deploy block, also emit a self-contained release bundle
	// (deploy.sh + a runtime Dockerfile + one manifest per k8s node) next to the configs.
	// No deploy blocks ⇒ nothing extra is written (backward compatible).
	if release.HasDeploy(net) {
		plan, err := release.BuildPlan(net, nodes, moduleRoot(), filepath.Base(*netFlag))
		if err != nil {
			return err
		}
		arts, err := plan.Render()
		if err != nil {
			return err
		}
		for _, a := range arts {
			dst := filepath.Join(*outFlag, a.Name)
			if err := os.WriteFile(dst, a.Data, a.Mode); err != nil {
				return err
			}
			fmt.Printf("wrote %s\n", dst)
		}
	}
	return nil
}

// moduleRoot walks up from the working directory to the directory containing go.mod (where
// deploy.sh will `go build .`), falling back to the working directory. The result is baked
// into deploy.sh as REPO_ROOT and can be overridden at deploy time via $DUALNET_REPO.
func moduleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return "."
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			cwd, _ := os.Getwd()
			return cwd
		}
		dir = parent
	}
}
